#!/bin/bash
################################################################################
# Cursor Logs Organization Script
# Automatically organizes markdown and txt files by date
# Part of CI/CD pipeline
################################################################################

set -e

# Get current date
CURRENT_DATE=$(date +%Y-%m-%d)
LOG_DIR="cursor-logs/${CURRENT_DATE}"

echo "📁 Organizing Cursor Logs for ${CURRENT_DATE}..."

# Create directory if it doesn't exist
mkdir -p "${LOG_DIR}"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

print_step() {
    echo -e "${BLUE}==>${NC} ${GREEN}$1${NC}"
}

# Function to move files with timestamp check
organize_files() {
    local pattern=$1
    local file_type=$2
    local count=0
    
    # Find files modified today (excluding cursor-logs directory)
    find . -maxdepth 1 -type f -name "${pattern}" -not -path "./cursor-logs/*" -mtime 0 2>/dev/null | while read -r file; do
        if [ -f "$file" ]; then
            filename=$(basename "$file")
            
            # Skip important files that shouldn't be moved
            if [ "$filename" != "README.md" ] && \
               [ "$filename" != "requirements.txt" ] && \
               [ "$filename" != "package.json" ] && \
               [ "$filename" != "package-lock.json" ] && \
               [ "$filename" != "tsconfig.json" ] && \
               [ "$filename" != "next.config.js" ] && \
               [ "$filename" != "tailwind.config.ts" ] && \
               [ "$filename" != "postcss.config.js" ] && \
               [ "$filename" != "vercel.json" ] && \
               [ "$filename" != "Dockerfile" ] && \
               [ "$filename" != "next-env.d.ts" ]; then
                
                # Move file to dated directory
                mv "$file" "${LOG_DIR}/"
                echo "  📄 Moved: $filename"
                count=$((count + 1))
            fi
        fi
    done
}

# Organize markdown files
print_step "Organizing Markdown files..."
organize_files "*.md" "Markdown"

# Organize text files
print_step "Organizing Text files..."
organize_files "*.txt" "Text"

# Organize shell scripts (except important ones)
print_step "Organizing Shell scripts..."
find . -maxdepth 1 -type f -name "*.sh" -not -path "./cursor-logs/*" -mtime 0 2>/dev/null | while read -r file; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        
        # Skip setup and start scripts
        if [ "$filename" != "runpod-setup.sh" ] && \
           [ "$filename" != "runpod-install-colmap.sh" ]; then
            
            # Move file to dated directory
            mv "$file" "${LOG_DIR}/"
            echo "  📄 Moved: $filename"
        fi
    fi
done

# Create a session summary
print_step "Creating session summary..."

cat > "${LOG_DIR}/SESSION_SUMMARY.md" << EOF
# Session Summary - ${CURRENT_DATE}

## Overview

This directory contains all Cursor-generated documentation and logs from the development session on ${CURRENT_DATE}.

## Files Organized

\`\`\`
$(ls -1 "${LOG_DIR}")
\`\`\`

## Session Information

- **Date**: ${CURRENT_DATE}
- **Repository**: colmap-demo
- **GitHub**: https://github.com/marco-interact/colmap-demo.git

## Key Documentation

Check the files in this directory for:
- Deployment guides
- Setup instructions
- Configuration changes
- Development notes
- Troubleshooting guides

---

*Auto-generated by organize-cursor-logs.sh*
EOF

echo ""
echo "✅ Cursor logs organized successfully!"
echo "📂 Location: ${LOG_DIR}"
echo ""

